django/rango/project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from rango import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rango/', include('rango.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/rango/rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='category'),
    url(r'^add_page/(?P<category_name_slug>[\w\-]+)/$', views.add_page, name='add_page'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

django/rango/rango/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


class Category(models.Model):
    name_max_length = 128

    name = models.CharField(max_length=name_max_length, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)

    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

django/rango/rango/forms.py
from django import forms
from .models import Page, Category, UserProfile
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.name_max_length,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    # def clean_url(self):
    #     print("hi")
    #     cleaned_data = self.cleaned_data
    #     url = cleaned_data.get('url')
    #     print(url)
    #     if url and not url.startswith('http://'):
    #         url = 'http://' + url
    #         cleaned_data['url'] = url
    #
    #         return cleaned_data

django/rango/rango/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from .models import Page, Category
from .forms import CategoryForm, PageForm
from django.http import HttpResponseRedirect, HttpResponse
from rango.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by("-views")[:5]
    context_dict = {'categories': category_list, 'pages': page_list}
    return render(request, 'rango/index.html', context=context_dict)


def about(request):
    return render(request, 'rango/about.html')


def show_category(request, category_name_slug):
    context_dict = {}
    category = get_object_or_404(Category, slug=category_name_slug)
    pages = Page.objects.filter(category=category)
    context_dict['pages'] = pages
    context_dict['category'] = category
    return render(request, 'rango/category.html', context_dict)


@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    category = get_object_or_404(Category, slug=category_name_slug)

    form = PageForm()

    if request.method == 'POST':
        print(request.POST)
        form = PageForm(request.POST)
        if form.is_valid():
            print("Is valid")
            page = form.save(commit=False)
            page.category = category
            page.views = 0
            page.save()
            return HttpResponseRedirect(reverse('rango:category', args=(category.slug,)))
        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('rango:index'))


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'rango/register.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your Rando account is disabled")
        else:
            print("Invalid login details: {0}, {1}".format(username,password))
            return HttpResponse("Invalid login details supplies")
    else:
        return render(request, 'rango/login.html', {})

django/rango/rango/templates/rango/about.html
{% extends 'rango/base.html' %}

{% block title_block %}
    About
{% endblock %}

{% block content %}
    <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a cat?" />
    <div>This tutorial has been put together by Nick</div>
{% endblock %}

django/rango/rango/templates/rango/add_category.html
{% extends 'rango/base.html' %}

{% block title_block %}
    Adding a new category
{% endblock %}

{% block content %}
    <h1>Add a Category</h1>
<div>
    <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{  hidden }}
        {% endfor %}
        {%  for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }} <br />
        {% endfor %}
        <input type="submit" name="submit" value="Create Category" />
    </form>
</div>
{%  endblock %}

django/rango/rango/templates/rango/add_page.html
{% extends 'rango/base.html' %}

{% block title_block %}
    Adding page to {{ category.name }}
{% endblock %}

{% block content %}
    <h1>Add a Page</h1>
    <div>
        <form id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{  hidden }}
            {% endfor %}
            {%  for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }} <br />
            {% endfor %}
            <input type="submit" name="submit" value="Create Page" />
        </form>
    </div>
{% endblock %}

django/rango/rango/templates/rango/base.html
<!DOCTYPE html>
{% load rango_template_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        Rango -
        {% block title_block %}
            Tango with Django
        {% endblock %}
    </title>
</head>
<body>
<div>
{#    {% block sidebar_block %}#}
{#        {% get_category_list category %}#}
{#    {% endblock %}#}
</div>
    {% block content %}
    {% endblock %}
<hr />
<div>
    <ul>
        {% if user.is_authenticated %}
            <li><a href="{% url 'rango:logout' %}">Logout</a></li>
            <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
        {% else %}
            <li><a href="{% url 'rango:login' %}">Sign In</a></li>
            <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
        {% endif %}
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a href="{% url 'rango:aindex' %}">Index</a></li>
    </ul>
</div>
</body>
</html>

django/rango/rango/templates/rango/category.html
{% extends 'rango/base.html' %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block content %}
    <div>
        {% if category %}
            <h1>{{ category.name }}</h1>
            {% if pages %}
                <ul>
                {%  for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
                </ul>
            {% else %}
                <strong>No pages currently in category</strong>
            {% endif %}
        {% else %}
            The specified category does not exist
        {% endif %}
    </div>
    {% if user.is_authenticated %}
        <a href="{% url 'rango:add_page' category.slug %}">Create a new page</a> <br />
    {% endif %}
{% endblock %}

django/rango/rango/templates/rango/cats.html
<ul>
    {% if cats %}
        {%  for c in cats %}
            {% if c == act_cat %}
                <li>
                    <strong><a href="{% url 'rango:category' c.slug %}">{{ c.name }}</a></strong>
                </li>
            {% else %}
                <li><a href="{% url 'rango:category' c.slug %}">{{ c.name }}</a> </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present</strong></li>
    {% endif %}
</ul>

django/rango/rango/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block content %}
    <h1>Rango says...</h1>
    <div>
        {% if user.is_suthenticated %}
            howdy {{ user.username }}!
        {% else %}
            hey there partner!
        {% endif %}
    </div>
    <div>
        {% if categories %}
            <strong>Most liked categories:</strong>
            <ul>
                {% for category in categories %}
                    <li><a href="{% url 'rango:category' category.slug %}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no categories present</strong>
        {% endif %}
    </div>
    <div>
        {% if pages %}
            <strong>Most viewed pages</strong>
            <ul>
                {% for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no pages present</strong>
        {% endif %}
    </div>
    <div>
        <img src="{% static "rango/images/rango.jpg" %}"
             alt="Picture of Rango" />
{% endblock %}

django/rango/rango/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block content %}
    <h1>Login to Rango</h1>
    <form id="login_form" method="post" action="{% url 'rango:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50" />
        <br />
        Password: <input type="password" name="password" value="" size="50" />
        <br />
        <input type="submit" value="submit" />
    </form>
{% endblock %}

django/rango/rango/templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block content %}
    <h1>About Page</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
    {% else %}
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}